[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
okaform = "DC6BMdAaZVUuPKG2jDMnMUSb7AqYiiSUpjtScCnSui5V"

[programs.devnet]
okaform = "DC6BMdAaZVUuPKG2jDMnMUSb7AqYiiSUpjtScCnSui5V"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
